using RemoteFlow.Application.Services;
using Xunit;

namespace RemoteFlow.Application.Tests;

/// <summary>This parser is the whole of RemoteFlow's argument that an installer it is about to run is the
/// one the release published. A digest read wrongly is worse than no digest at all: it would either refuse
/// every genuine release, or — the case worth pinning hardest — accept a 64-character prefix of something
/// longer and call it a match.</summary>
public sealed class Sha256ChecksumsTests
{
    /// <summary>Exactly what `sha256sum *.zip *.exe | sort -k 2` writes, down to the two spaces and the LF
    /// line endings, because that is the command in .github/workflows/release.yml.</summary>
    private const string _released =
        "3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b  RemoteFlow-0.3.0-win-arm64-setup.exe\n" +
        "b1946ac92492d2347c6235b4d2611184b1946ac92492d2347c6235b4d2611184  RemoteFlow-0.3.0-win-arm64.zip\n" +
        "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  RemoteFlow-0.3.0-win-x64-setup.exe\n" +
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  RemoteFlow-0.3.0-win-x64.zip\n";

    [Fact]
    public void TheDigestForOneArtefactIsFoundAmongTheOthers()
    {
        Assert.True(Sha256Checksums.TryFind(_released, "RemoteFlow-0.3.0-win-x64-setup.exe", out var digest));
        Assert.Equal("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03", digest);
    }

    [Fact]
    public void AnArtefactTheFileDoesNotListIsNotFound()
    {
        // The release published no installer for this architecture. Refusing is the point: there is no
        // hash to check the download against, so there is nothing to run.
        Assert.False(Sha256Checksums.TryFind(_released, "RemoteFlow-0.3.0-win-x86-setup.exe", out var digest));
        Assert.Null(digest);
    }

    [Theory]
    // Binary mode, which sha256sum writes when it is passed -b.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03 *RemoteFlow.exe")]
    // A checkout with autocrlf on, or a pass through an editor.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  RemoteFlow.exe\r")]
    // A single space rather than two. Not what sha256sum writes, but not worth refusing a release over.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03 RemoteFlow.exe")]
    [InlineData("\n\n5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  RemoteFlow.exe\n\n")]
    [InlineData("# generated by CI\n5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  RemoteFlow.exe")]
    public void TheSeparatorsAndSurroundingsThatVaryAreAllAccepted(string content)
    {
        Assert.True(Sha256Checksums.TryFind(content, "RemoteFlow.exe", out var digest));
        Assert.Equal("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03", digest);
    }

    [Fact]
    public void AnUppercaseDigestComesBackLowercase()
    {
        // It is compared against ToHexStringLower output, so the case has to be settled here rather than at
        // every call site.
        const string content = "5891B5B522D5DF086D0FF0B110FBD9D21BB4FC7163AF34D08286A2E846F6BE03  RemoteFlow.exe";

        Assert.True(Sha256Checksums.TryFind(content, "RemoteFlow.exe", out var digest));
        Assert.Equal("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03", digest);
    }

    [Fact]
    public void TheFilenameIsMatchedWithoutRegardToCase()
    {
        Assert.True(Sha256Checksums.TryFind(_released, "remoteflow-0.3.0-WIN-X64-setup.EXE", out _));
    }

    [Theory]
    // Sixty-three characters: too short to be a digest.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be0  RemoteFlow.exe")]
    // Sixty-five. The one that matters: a naive parser reads the first sixty-four and treats the rest as
    // the start of a filename, so a corrupted line would silently become a match against the wrong hash.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be035  RemoteFlow.exe")]
    // Not hex.
    [InlineData("zzz1b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  RemoteFlow.exe")]
    // A digest and nothing else.
    [InlineData("5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03")]
    // GNU's escaped-filename form. Understood well enough to skip, not well enough to trust.
    [InlineData("\\5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03  Remote\\nFlow.exe")]
    [InlineData("")]
    [InlineData("not a checksums file at all")]
    public void ALineThatIsNotADigestAndANameIsSkipped(string content)
    {
        Assert.False(Sha256Checksums.TryFind(content, "RemoteFlow.exe", out var digest));
        Assert.Null(digest);
    }

    [Fact]
    public void AnUnparseableLineDoesNotHideTheLinesAfterIt()
    {
        // CI writes this file, but the parser reads it after a network fetch. One line it cannot read must
        // cost that line and nothing else.
        var content = "garbage\n" + _released;

        Assert.True(Sha256Checksums.TryFind(content, "RemoteFlow-0.3.0-win-x64-setup.exe", out _));
    }
}
