// <auto-generated />
// Transcribed from the MSTSCLib type library in C:\Windows\System32\mstscax.dll (Windows 11, build
// 10.0.28000.2525) by tools/RemoteFlow.RdpSpike/README.md's type-library dump, then checked in as source.
// ADR-0017 records why the interop is hand-held source rather than a <COMReference> build step.
//
// Every member is [PreserveSig] and returns the raw HRESULT: the spike wants to see failure codes, not
// exceptions synthesised by the marshaller. The `slot` comments are the vtable offsets the type library
// reports; the order of the declarations below IS the ABI and must not be rearranged. A dual interface
// arrives from the type library already flattened, so IMsRdpClient10 carries every inherited member of
// IMsTscAx through IMsRdpClient9 in one declaration.
//
// Interface pointers come back as IntPtr rather than a typed reference so ownership is explicit: the
// caller wraps with Marshal.GetObjectForIUnknown and releases the raw pointer itself.

using System.Runtime.InteropServices;

namespace RemoteFlow.RdpSpike.Interop;
[ComImport]
[Guid("7ed92c39-eb38-4927-a70a-708ac5a59321")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IMsRdpClient10
{
    // IDispatch slots 3-6. Declared so the vtable offsets below line up.
    [PreserveSig] int GetTypeInfoCount(out uint pctinfo);
    [PreserveSig] int GetTypeInfo(uint itinfo, uint lcid, out IntPtr pptinfo);
    [PreserveSig] int GetIDsOfNames(in Guid riid, IntPtr rgszNames, uint cNames, uint lcid, IntPtr rgdispid);
    [PreserveSig] int Invoke(int dispid, in Guid riid, uint lcid, ushort flags, IntPtr pdispparams, IntPtr pvarResult, IntPtr pexcepinfo, IntPtr puArgErr);

    [PreserveSig] int put_Server([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 1, slot 7
    [PreserveSig] int get_Server([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 1, slot 8
    [PreserveSig] int put_Domain([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 2, slot 9
    [PreserveSig] int get_Domain([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 2, slot 10
    [PreserveSig] int put_UserName([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 3, slot 11
    [PreserveSig] int get_UserName([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 3, slot 12
    [PreserveSig] int put_DisconnectedText([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 4, slot 13
    [PreserveSig] int get_DisconnectedText([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 4, slot 14
    [PreserveSig] int put_ConnectingText([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 5, slot 15
    [PreserveSig] int get_ConnectingText([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 5, slot 16
    [PreserveSig] int get_Connected(out short pRetVal); // dispid 6, slot 17
    [PreserveSig] int put_DesktopWidth(int arg0); // dispid 12, slot 18
    [PreserveSig] int get_DesktopWidth(out int pRetVal); // dispid 12, slot 19
    [PreserveSig] int put_DesktopHeight(int arg0); // dispid 13, slot 20
    [PreserveSig] int get_DesktopHeight(out int pRetVal); // dispid 13, slot 21
    [PreserveSig] int put_StartConnected(int arg0); // dispid 16, slot 22
    [PreserveSig] int get_StartConnected(out int pRetVal); // dispid 16, slot 23
    [PreserveSig] int get_HorizontalScrollBarVisible(out int pRetVal); // dispid 17, slot 24
    [PreserveSig] int get_VerticalScrollBarVisible(out int pRetVal); // dispid 18, slot 25
    [PreserveSig] int put_FullScreenTitle([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 19, slot 26
    [PreserveSig] int get_CipherStrength(out int pRetVal); // dispid 20, slot 27
    [PreserveSig] int get_Version([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 21, slot 28
    [PreserveSig] int get_SecuredSettingsEnabled(out int pRetVal); // dispid 22, slot 29
    [PreserveSig] int get_SecuredSettings(out IntPtr /* IMsTscSecuredSettings */ pRetVal); // dispid 97, slot 30
    [PreserveSig] int get_AdvancedSettings(out IntPtr /* IMsTscAdvancedSettings */ pRetVal); // dispid 98, slot 31
    [PreserveSig] int get_Debugger(out IntPtr /* IMsTscDebug */ pRetVal); // dispid 99, slot 32
    [PreserveSig] int Connect(); // dispid 30, slot 33
    [PreserveSig] int Disconnect(); // dispid 31, slot 34
    [PreserveSig] int CreateVirtualChannels([MarshalAs(UnmanagedType.BStr)] string newVal); // dispid 33, slot 35
    [PreserveSig] int SendOnVirtualChannel([MarshalAs(UnmanagedType.BStr)] string chanName, [MarshalAs(UnmanagedType.BStr)] string ChanData); // dispid 34, slot 36
    [PreserveSig] int put_ColorDepth(int arg0); // dispid 100, slot 37
    [PreserveSig] int get_ColorDepth(out int pRetVal); // dispid 100, slot 38
    [PreserveSig] int get_AdvancedSettings2(out IntPtr /* IMsRdpClientAdvancedSettings */ pRetVal); // dispid 101, slot 39
    [PreserveSig] int get_SecuredSettings2(out IntPtr /* IMsRdpClientSecuredSettings */ pRetVal); // dispid 102, slot 40
    [PreserveSig] int get_ExtendedDisconnectReason(out int /* ExtendedDisconnectReasonCode */ pRetVal); // dispid 103, slot 41
    [PreserveSig] int put_FullScreen(short arg0); // dispid 104, slot 42
    [PreserveSig] int get_FullScreen(out short pRetVal); // dispid 104, slot 43
    [PreserveSig] int SetVirtualChannelOptions([MarshalAs(UnmanagedType.BStr)] string chanName, int chanOptions); // dispid 35, slot 44
    [PreserveSig] int GetVirtualChannelOptions([MarshalAs(UnmanagedType.BStr)] string chanName, out int pRetVal); // dispid 36, slot 45
    [PreserveSig] int RequestClose(out int /* ControlCloseStatus */ pRetVal); // dispid 37, slot 46
    [PreserveSig] int get_AdvancedSettings3(out IntPtr /* IMsRdpClientAdvancedSettings2 */ pRetVal); // dispid 200, slot 47
    [PreserveSig] int put_ConnectedStatusText([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 201, slot 48
    [PreserveSig] int get_ConnectedStatusText([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 201, slot 49
    [PreserveSig] int get_AdvancedSettings4(out IntPtr /* IMsRdpClientAdvancedSettings3 */ pRetVal); // dispid 300, slot 50
    [PreserveSig] int get_AdvancedSettings5(out IntPtr /* IMsRdpClientAdvancedSettings4 */ pRetVal); // dispid 400, slot 51
    [PreserveSig] int get_TransportSettings(out IntPtr /* IMsRdpClientTransportSettings */ pRetVal); // dispid 500, slot 52
    [PreserveSig] int get_AdvancedSettings6(out IntPtr /* IMsRdpClientAdvancedSettings5 */ pRetVal); // dispid 502, slot 53
    [PreserveSig] int GetErrorDescription(uint disconnectReason, uint ExtendedDisconnectReason, [MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 503, slot 54
    [PreserveSig] int get_RemoteProgram(out IntPtr /* ITSRemoteProgram */ pRetVal); // dispid 504, slot 55
    [PreserveSig] int get_MsRdpClientShell(out IntPtr /* IMsRdpClientShell */ pRetVal); // dispid 505, slot 56
    [PreserveSig] int get_AdvancedSettings7(out IntPtr /* IMsRdpClientAdvancedSettings6 */ pRetVal); // dispid 507, slot 57
    [PreserveSig] int get_TransportSettings2(out IntPtr /* IMsRdpClientTransportSettings2 */ pRetVal); // dispid 506, slot 58
    [PreserveSig] int get_AdvancedSettings8(out IntPtr /* IMsRdpClientAdvancedSettings7 */ pRetVal); // dispid 600, slot 59
    [PreserveSig] int get_TransportSettings3(out IntPtr /* IMsRdpClientTransportSettings3 */ pRetVal); // dispid 601, slot 60
    [PreserveSig] int GetStatusText(uint statusCode, [MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 602, slot 61
    [PreserveSig] int get_SecuredSettings3(out IntPtr /* IMsRdpClientSecuredSettings2 */ pRetVal); // dispid 603, slot 62
    [PreserveSig] int get_RemoteProgram2(out IntPtr /* ITSRemoteProgram2 */ pRetVal); // dispid 604, slot 63
    [PreserveSig] int SendRemoteAction(int /* RemoteSessionActionType */ actionType); // dispid 700, slot 64
    [PreserveSig] int get_AdvancedSettings9(out IntPtr /* IMsRdpClientAdvancedSettings8 */ pRetVal); // dispid 701, slot 65
    [PreserveSig] int Reconnect(uint ulWidth, uint ulHeight, out int /* ControlReconnectStatus */ pRetVal); // dispid 702, slot 66
    [PreserveSig] int get_TransportSettings4(out IntPtr /* IMsRdpClientTransportSettings4 */ pRetVal); // dispid 800, slot 67
    [PreserveSig] int SyncSessionDisplaySettings(); // dispid 801, slot 68
    [PreserveSig] int UpdateSessionDisplaySettings(uint ulDesktopWidth, uint ulDesktopHeight, uint ulPhysicalWidth, uint ulPhysicalHeight, uint ulOrientation, uint ulDesktopScaleFactor, uint ulDeviceScaleFactor); // dispid 802, slot 69
    [PreserveSig] int attachEvent([MarshalAs(UnmanagedType.BStr)] string eventName, [MarshalAs(UnmanagedType.IDispatch)] object callback); // dispid 803, slot 70
    [PreserveSig] int detachEvent([MarshalAs(UnmanagedType.BStr)] string eventName, [MarshalAs(UnmanagedType.IDispatch)] object callback); // dispid 804, slot 71
    [PreserveSig] int get_RemoteProgram3(out IntPtr /* ITSRemoteProgram3 */ pRetVal); // dispid 900, slot 72
}

[ComImport]
[Guid("4f6996d5-d7b1-412c-b0ff-063718566907")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IMsRdpClientNonScriptable5
{
    [PreserveSig] int put_ClearTextPassword([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 1, slot 3
    [PreserveSig] int put_PortablePassword([MarshalAs(UnmanagedType.BStr)] string pPortablePass); // dispid 2, slot 4
    [PreserveSig] int get_PortablePassword([MarshalAs(UnmanagedType.BStr)] out string pPortablePass); // dispid 2, slot 5
    [PreserveSig] int put_PortableSalt([MarshalAs(UnmanagedType.BStr)] string pPortableSalt); // dispid 3, slot 6
    [PreserveSig] int get_PortableSalt([MarshalAs(UnmanagedType.BStr)] out string pPortableSalt); // dispid 3, slot 7
    [PreserveSig] int put_BinaryPassword([MarshalAs(UnmanagedType.BStr)] string pBinaryPassword); // dispid 4, slot 8
    [PreserveSig] int get_BinaryPassword([MarshalAs(UnmanagedType.BStr)] out string pBinaryPassword); // dispid 4, slot 9
    [PreserveSig] int put_BinarySalt([MarshalAs(UnmanagedType.BStr)] string pSalt); // dispid 5, slot 10
    [PreserveSig] int get_BinarySalt([MarshalAs(UnmanagedType.BStr)] out string pSalt); // dispid 5, slot 11
    [PreserveSig] int ResetPassword(); // dispid 10, slot 12
    [PreserveSig] int NotifyRedirectDeviceChange(int /* UINT_PTR */ wParam, int /* LONG_PTR */ lParam); // dispid 11, slot 13
    [PreserveSig] int SendKeys(int numKeys, in short pbArrayKeyUp, in int plKeyData); // dispid 12, slot 14
    [PreserveSig] int put_UIParentWindowHandle(int /* wireHWND */ phwndUIParentWindowHandle); // dispid 13, slot 15
    [PreserveSig] int get_UIParentWindowHandle(out int /* wireHWND */ phwndUIParentWindowHandle); // dispid 13, slot 16
    [PreserveSig] int put_ShowRedirectionWarningDialog(short pfShowRdrDlg); // dispid 14, slot 17
    [PreserveSig] int get_ShowRedirectionWarningDialog(out short pfShowRdrDlg); // dispid 14, slot 18
    [PreserveSig] int put_PromptForCredentials(short pfPrompt); // dispid 15, slot 19
    [PreserveSig] int get_PromptForCredentials(out short pfPrompt); // dispid 15, slot 20
    [PreserveSig] int put_NegotiateSecurityLayer(short pfNegotiate); // dispid 16, slot 21
    [PreserveSig] int get_NegotiateSecurityLayer(out short pfNegotiate); // dispid 16, slot 22
    [PreserveSig] int put_EnableCredSspSupport(short pfEnableSupport); // dispid 17, slot 23
    [PreserveSig] int get_EnableCredSspSupport(out short pfEnableSupport); // dispid 17, slot 24
    [PreserveSig] int put_RedirectDynamicDrives(short pfRedirectDynamicDrives); // dispid 21, slot 25
    [PreserveSig] int get_RedirectDynamicDrives(out short pfRedirectDynamicDrives); // dispid 21, slot 26
    [PreserveSig] int put_RedirectDynamicDevices(short pfRedirectDynamicDevices); // dispid 20, slot 27
    [PreserveSig] int get_RedirectDynamicDevices(out short pfRedirectDynamicDevices); // dispid 20, slot 28
    [PreserveSig] int get_DeviceCollection(out IntPtr /* vt=VT_PTR */ ppDeviceCollection); // dispid 18, slot 29
    [PreserveSig] int get_DriveCollection(out IntPtr /* vt=VT_PTR */ ppDeviceCollection); // dispid 19, slot 30
    [PreserveSig] int put_WarnAboutSendingCredentials(short pfWarn); // dispid 23, slot 31
    [PreserveSig] int get_WarnAboutSendingCredentials(out short pfWarn); // dispid 23, slot 32
    [PreserveSig] int put_WarnAboutClipboardRedirection(short pfWarn); // dispid 22, slot 33
    [PreserveSig] int get_WarnAboutClipboardRedirection(out short pfWarn); // dispid 22, slot 34
    [PreserveSig] int put_ConnectionBarText([MarshalAs(UnmanagedType.BStr)] string pConnectionBarText); // dispid 24, slot 35
    [PreserveSig] int get_ConnectionBarText([MarshalAs(UnmanagedType.BStr)] out string pConnectionBarText); // dispid 24, slot 36
    [PreserveSig] int put_RedirectionWarningType(int /* RedirectionWarningType */ pWrnType); // dispid 25, slot 37
    [PreserveSig] int get_RedirectionWarningType(out int /* RedirectionWarningType */ pWrnType); // dispid 25, slot 38
    [PreserveSig] int put_MarkRdpSettingsSecure(short pfRdpSecure); // dispid 28, slot 39
    [PreserveSig] int get_MarkRdpSettingsSecure(out short pfRdpSecure); // dispid 28, slot 40
    [PreserveSig] int put_PublisherCertificateChain([MarshalAs(UnmanagedType.Struct)] in object pVarCert); // dispid 26, slot 41
    [PreserveSig] int get_PublisherCertificateChain([MarshalAs(UnmanagedType.Struct)] out object pVarCert); // dispid 26, slot 42
    [PreserveSig] int put_WarnAboutPrinterRedirection(short pfWarn); // dispid 27, slot 43
    [PreserveSig] int get_WarnAboutPrinterRedirection(out short pfWarn); // dispid 27, slot 44
    [PreserveSig] int put_AllowCredentialSaving(short pfAllowSave); // dispid 29, slot 45
    [PreserveSig] int get_AllowCredentialSaving(out short pfAllowSave); // dispid 29, slot 46
    [PreserveSig] int put_PromptForCredsOnClient(short pfPromptForCredsOnClient); // dispid 30, slot 47
    [PreserveSig] int get_PromptForCredsOnClient(out short pfPromptForCredsOnClient); // dispid 30, slot 48
    [PreserveSig] int put_LaunchedViaClientShellInterface(short pfLaunchedViaClientShellInterface); // dispid 31, slot 49
    [PreserveSig] int get_LaunchedViaClientShellInterface(out short pfLaunchedViaClientShellInterface); // dispid 31, slot 50
    [PreserveSig] int put_TrustedZoneSite(short pfIsTrustedZone); // dispid 32, slot 51
    [PreserveSig] int get_TrustedZoneSite(out short pfIsTrustedZone); // dispid 32, slot 52
    [PreserveSig] int put_UseMultimon(short pfUseMultimon); // dispid 33, slot 53
    [PreserveSig] int get_UseMultimon(out short pfUseMultimon); // dispid 33, slot 54
    [PreserveSig] int get_RemoteMonitorCount(out uint pcRemoteMonitors); // dispid 35, slot 55
    [PreserveSig] int GetRemoteMonitorsBoundingBox(out int pLeft, out int pTop, out int pRight, out int pBottom); // dispid 36, slot 56
    [PreserveSig] int get_RemoteMonitorLayoutMatchesLocal(out short pfRemoteMatchesLocal); // dispid 37, slot 57
    [PreserveSig] int put_DisableConnectionBar(short arg0); // dispid 38, slot 58
    [PreserveSig] int put_DisableRemoteAppCapsCheck(short pfDisableRemoteAppCapsCheck); // dispid 39, slot 59
    [PreserveSig] int get_DisableRemoteAppCapsCheck(out short pfDisableRemoteAppCapsCheck); // dispid 39, slot 60
    [PreserveSig] int put_WarnAboutDirectXRedirection(short pfWarn); // dispid 40, slot 61
    [PreserveSig] int get_WarnAboutDirectXRedirection(out short pfWarn); // dispid 40, slot 62
    [PreserveSig] int put_AllowPromptingForCredentials(short pfAllow); // dispid 41, slot 63
    [PreserveSig] int get_AllowPromptingForCredentials(out short pfAllow); // dispid 41, slot 64
}

[ComImport]
[Guid("302d8188-0052-4807-806a-362b628f9ac5")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IMsRdpExtendedSettings
{
    [PreserveSig] int put_Property([MarshalAs(UnmanagedType.BStr)] string bstrPropertyName, [MarshalAs(UnmanagedType.Struct)] in object pValue); // dispid 1, slot 3
    [PreserveSig] int get_Property([MarshalAs(UnmanagedType.BStr)] string bstrPropertyName, [MarshalAs(UnmanagedType.Struct)] out object pValue); // dispid 1, slot 4
}

[ComImport]
[Guid("89acb528-2557-4d16-8625-226a30e97e9a")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IMsRdpClientAdvancedSettings8
{
    // IDispatch slots 3-6. Declared so the vtable offsets below line up.
    [PreserveSig] int GetTypeInfoCount(out uint pctinfo);
    [PreserveSig] int GetTypeInfo(uint itinfo, uint lcid, out IntPtr pptinfo);
    [PreserveSig] int GetIDsOfNames(in Guid riid, IntPtr rgszNames, uint cNames, uint lcid, IntPtr rgdispid);
    [PreserveSig] int Invoke(int dispid, in Guid riid, uint lcid, ushort flags, IntPtr pdispparams, IntPtr pvarResult, IntPtr pexcepinfo, IntPtr puArgErr);

    [PreserveSig] int put_Compress(int arg0); // dispid 121, slot 7
    [PreserveSig] int get_Compress(out int pRetVal); // dispid 121, slot 8
    [PreserveSig] int put_BitmapPeristence(int arg0); // dispid 122, slot 9
    [PreserveSig] int get_BitmapPeristence(out int pRetVal); // dispid 122, slot 10
    [PreserveSig] int put_allowBackgroundInput(int arg0); // dispid 161, slot 11
    [PreserveSig] int get_allowBackgroundInput(out int pRetVal); // dispid 161, slot 12
    [PreserveSig] int put_KeyBoardLayoutStr([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 162, slot 13
    [PreserveSig] int put_PluginDlls([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 170, slot 14
    [PreserveSig] int put_IconFile([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 171, slot 15
    [PreserveSig] int put_IconIndex(int arg0); // dispid 172, slot 16
    [PreserveSig] int put_ContainerHandledFullScreen(int arg0); // dispid 173, slot 17
    [PreserveSig] int get_ContainerHandledFullScreen(out int pRetVal); // dispid 173, slot 18
    [PreserveSig] int put_DisableRdpdr(int arg0); // dispid 174, slot 19
    [PreserveSig] int get_DisableRdpdr(out int pRetVal); // dispid 174, slot 20
    [PreserveSig] int put_SmoothScroll(int arg0); // dispid 101, slot 21
    [PreserveSig] int get_SmoothScroll(out int pRetVal); // dispid 101, slot 22
    [PreserveSig] int put_AcceleratorPassthrough(int arg0); // dispid 102, slot 23
    [PreserveSig] int get_AcceleratorPassthrough(out int pRetVal); // dispid 102, slot 24
    [PreserveSig] int put_ShadowBitmap(int arg0); // dispid 103, slot 25
    [PreserveSig] int get_ShadowBitmap(out int pRetVal); // dispid 103, slot 26
    [PreserveSig] int put_TransportType(int arg0); // dispid 104, slot 27
    [PreserveSig] int get_TransportType(out int pRetVal); // dispid 104, slot 28
    [PreserveSig] int put_SasSequence(int arg0); // dispid 105, slot 29
    [PreserveSig] int get_SasSequence(out int pRetVal); // dispid 105, slot 30
    [PreserveSig] int put_EncryptionEnabled(int arg0); // dispid 106, slot 31
    [PreserveSig] int get_EncryptionEnabled(out int pRetVal); // dispid 106, slot 32
    [PreserveSig] int put_DedicatedTerminal(int arg0); // dispid 107, slot 33
    [PreserveSig] int get_DedicatedTerminal(out int pRetVal); // dispid 107, slot 34
    [PreserveSig] int put_RDPPort(int arg0); // dispid 108, slot 35
    [PreserveSig] int get_RDPPort(out int pRetVal); // dispid 108, slot 36
    [PreserveSig] int put_EnableMouse(int arg0); // dispid 109, slot 37
    [PreserveSig] int get_EnableMouse(out int pRetVal); // dispid 109, slot 38
    [PreserveSig] int put_DisableCtrlAltDel(int arg0); // dispid 110, slot 39
    [PreserveSig] int get_DisableCtrlAltDel(out int pRetVal); // dispid 110, slot 40
    [PreserveSig] int put_EnableWindowsKey(int arg0); // dispid 111, slot 41
    [PreserveSig] int get_EnableWindowsKey(out int pRetVal); // dispid 111, slot 42
    [PreserveSig] int put_DoubleClickDetect(int arg0); // dispid 112, slot 43
    [PreserveSig] int get_DoubleClickDetect(out int pRetVal); // dispid 112, slot 44
    [PreserveSig] int put_MaximizeShell(int arg0); // dispid 113, slot 45
    [PreserveSig] int get_MaximizeShell(out int pRetVal); // dispid 113, slot 46
    [PreserveSig] int put_HotKeyFullScreen(int arg0); // dispid 114, slot 47
    [PreserveSig] int get_HotKeyFullScreen(out int pRetVal); // dispid 114, slot 48
    [PreserveSig] int put_HotKeyCtrlEsc(int arg0); // dispid 115, slot 49
    [PreserveSig] int get_HotKeyCtrlEsc(out int pRetVal); // dispid 115, slot 50
    [PreserveSig] int put_HotKeyAltEsc(int arg0); // dispid 116, slot 51
    [PreserveSig] int get_HotKeyAltEsc(out int pRetVal); // dispid 116, slot 52
    [PreserveSig] int put_HotKeyAltTab(int arg0); // dispid 117, slot 53
    [PreserveSig] int get_HotKeyAltTab(out int pRetVal); // dispid 117, slot 54
    [PreserveSig] int put_HotKeyAltShiftTab(int arg0); // dispid 118, slot 55
    [PreserveSig] int get_HotKeyAltShiftTab(out int pRetVal); // dispid 118, slot 56
    [PreserveSig] int put_HotKeyAltSpace(int arg0); // dispid 119, slot 57
    [PreserveSig] int get_HotKeyAltSpace(out int pRetVal); // dispid 119, slot 58
    [PreserveSig] int put_HotKeyCtrlAltDel(int arg0); // dispid 120, slot 59
    [PreserveSig] int get_HotKeyCtrlAltDel(out int pRetVal); // dispid 120, slot 60
    [PreserveSig] int put_orderDrawThreshold(int arg0); // dispid 123, slot 61
    [PreserveSig] int get_orderDrawThreshold(out int pRetVal); // dispid 123, slot 62
    [PreserveSig] int put_BitmapCacheSize(int arg0); // dispid 124, slot 63
    [PreserveSig] int get_BitmapCacheSize(out int pRetVal); // dispid 124, slot 64
    [PreserveSig] int put_BitmapVirtualCacheSize(int arg0); // dispid 125, slot 65
    [PreserveSig] int get_BitmapVirtualCacheSize(out int pRetVal); // dispid 125, slot 66
    [PreserveSig] int put_ScaleBitmapCachesByBPP(int arg0); // dispid 175, slot 67
    [PreserveSig] int get_ScaleBitmapCachesByBPP(out int pRetVal); // dispid 175, slot 68
    [PreserveSig] int put_NumBitmapCaches(int arg0); // dispid 126, slot 69
    [PreserveSig] int get_NumBitmapCaches(out int pRetVal); // dispid 126, slot 70
    [PreserveSig] int put_CachePersistenceActive(int arg0); // dispid 127, slot 71
    [PreserveSig] int get_CachePersistenceActive(out int pRetVal); // dispid 127, slot 72
    [PreserveSig] int put_PersistCacheDirectory([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 138, slot 73
    [PreserveSig] int put_brushSupportLevel(int arg0); // dispid 156, slot 74
    [PreserveSig] int get_brushSupportLevel(out int pRetVal); // dispid 156, slot 75
    [PreserveSig] int put_minInputSendInterval(int arg0); // dispid 157, slot 76
    [PreserveSig] int get_minInputSendInterval(out int pRetVal); // dispid 157, slot 77
    [PreserveSig] int put_InputEventsAtOnce(int arg0); // dispid 158, slot 78
    [PreserveSig] int get_InputEventsAtOnce(out int pRetVal); // dispid 158, slot 79
    [PreserveSig] int put_maxEventCount(int arg0); // dispid 159, slot 80
    [PreserveSig] int get_maxEventCount(out int pRetVal); // dispid 159, slot 81
    [PreserveSig] int put_keepAliveInterval(int arg0); // dispid 160, slot 82
    [PreserveSig] int get_keepAliveInterval(out int pRetVal); // dispid 160, slot 83
    [PreserveSig] int put_shutdownTimeout(int arg0); // dispid 163, slot 84
    [PreserveSig] int get_shutdownTimeout(out int pRetVal); // dispid 163, slot 85
    [PreserveSig] int put_overallConnectionTimeout(int arg0); // dispid 164, slot 86
    [PreserveSig] int get_overallConnectionTimeout(out int pRetVal); // dispid 164, slot 87
    [PreserveSig] int put_singleConnectionTimeout(int arg0); // dispid 165, slot 88
    [PreserveSig] int get_singleConnectionTimeout(out int pRetVal); // dispid 165, slot 89
    [PreserveSig] int put_KeyboardType(int arg0); // dispid 166, slot 90
    [PreserveSig] int get_KeyboardType(out int pRetVal); // dispid 166, slot 91
    [PreserveSig] int put_KeyboardSubType(int arg0); // dispid 167, slot 92
    [PreserveSig] int get_KeyboardSubType(out int pRetVal); // dispid 167, slot 93
    [PreserveSig] int put_KeyboardFunctionKey(int arg0); // dispid 168, slot 94
    [PreserveSig] int get_KeyboardFunctionKey(out int pRetVal); // dispid 168, slot 95
    [PreserveSig] int put_WinceFixedPalette(int arg0); // dispid 169, slot 96
    [PreserveSig] int get_WinceFixedPalette(out int pRetVal); // dispid 169, slot 97
    [PreserveSig] int put_ConnectToServerConsole(short arg0); // dispid 178, slot 98
    [PreserveSig] int get_ConnectToServerConsole(out short pRetVal); // dispid 178, slot 99
    [PreserveSig] int put_BitmapPersistence(int arg0); // dispid 182, slot 100
    [PreserveSig] int get_BitmapPersistence(out int pRetVal); // dispid 182, slot 101
    [PreserveSig] int put_MinutesToIdleTimeout(int arg0); // dispid 183, slot 102
    [PreserveSig] int get_MinutesToIdleTimeout(out int pRetVal); // dispid 183, slot 103
    [PreserveSig] int put_SmartSizing(short arg0); // dispid 184, slot 104
    [PreserveSig] int get_SmartSizing(out short pRetVal); // dispid 184, slot 105
    [PreserveSig] int put_RdpdrLocalPrintingDocName([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 185, slot 106
    [PreserveSig] int get_RdpdrLocalPrintingDocName([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 185, slot 107
    [PreserveSig] int put_RdpdrClipCleanTempDirString([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 201, slot 108
    [PreserveSig] int get_RdpdrClipCleanTempDirString([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 201, slot 109
    [PreserveSig] int put_RdpdrClipPasteInfoString([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 202, slot 110
    [PreserveSig] int get_RdpdrClipPasteInfoString([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 202, slot 111
    [PreserveSig] int put_ClearTextPassword([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 186, slot 112
    [PreserveSig] int put_DisplayConnectionBar(short arg0); // dispid 187, slot 113
    [PreserveSig] int get_DisplayConnectionBar(out short pRetVal); // dispid 187, slot 114
    [PreserveSig] int put_PinConnectionBar(short arg0); // dispid 188, slot 115
    [PreserveSig] int get_PinConnectionBar(out short pRetVal); // dispid 188, slot 116
    [PreserveSig] int put_GrabFocusOnConnect(short arg0); // dispid 189, slot 117
    [PreserveSig] int get_GrabFocusOnConnect(out short pRetVal); // dispid 189, slot 118
    [PreserveSig] int put_LoadBalanceInfo([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 190, slot 119
    [PreserveSig] int get_LoadBalanceInfo([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 190, slot 120
    [PreserveSig] int put_RedirectDrives(short arg0); // dispid 191, slot 121
    [PreserveSig] int get_RedirectDrives(out short pRetVal); // dispid 191, slot 122
    [PreserveSig] int put_RedirectPrinters(short arg0); // dispid 192, slot 123
    [PreserveSig] int get_RedirectPrinters(out short pRetVal); // dispid 192, slot 124
    [PreserveSig] int put_RedirectPorts(short arg0); // dispid 193, slot 125
    [PreserveSig] int get_RedirectPorts(out short pRetVal); // dispid 193, slot 126
    [PreserveSig] int put_RedirectSmartCards(short arg0); // dispid 194, slot 127
    [PreserveSig] int get_RedirectSmartCards(out short pRetVal); // dispid 194, slot 128
    [PreserveSig] int put_BitmapVirtualCache16BppSize(int arg0); // dispid 195, slot 129
    [PreserveSig] int get_BitmapVirtualCache16BppSize(out int pRetVal); // dispid 195, slot 130
    [PreserveSig] int put_BitmapVirtualCache24BppSize(int arg0); // dispid 196, slot 131
    [PreserveSig] int get_BitmapVirtualCache24BppSize(out int pRetVal); // dispid 196, slot 132
    [PreserveSig] int put_PerformanceFlags(int arg0); // dispid 200, slot 133
    [PreserveSig] int get_PerformanceFlags(out int pRetVal); // dispid 200, slot 134
    [PreserveSig] int put_ConnectWithEndpoint([MarshalAs(UnmanagedType.Struct)] in object arg0); // dispid 203, slot 135
    [PreserveSig] int put_NotifyTSPublicKey(short arg0); // dispid 204, slot 136
    [PreserveSig] int get_NotifyTSPublicKey(out short pRetVal); // dispid 204, slot 137
    [PreserveSig] int get_CanAutoReconnect(out short pRetVal); // dispid 205, slot 138
    [PreserveSig] int put_EnableAutoReconnect(short arg0); // dispid 206, slot 139
    [PreserveSig] int get_EnableAutoReconnect(out short pRetVal); // dispid 206, slot 140
    [PreserveSig] int put_MaxReconnectAttempts(int arg0); // dispid 207, slot 141
    [PreserveSig] int get_MaxReconnectAttempts(out int pRetVal); // dispid 207, slot 142
    [PreserveSig] int put_ConnectionBarShowMinimizeButton(short arg0); // dispid 210, slot 143
    [PreserveSig] int get_ConnectionBarShowMinimizeButton(out short pRetVal); // dispid 210, slot 144
    [PreserveSig] int put_ConnectionBarShowRestoreButton(short arg0); // dispid 211, slot 145
    [PreserveSig] int get_ConnectionBarShowRestoreButton(out short pRetVal); // dispid 211, slot 146
    [PreserveSig] int put_AuthenticationLevel(uint arg0); // dispid 212, slot 147
    [PreserveSig] int get_AuthenticationLevel(out uint pRetVal); // dispid 212, slot 148
    [PreserveSig] int put_RedirectClipboard(short arg0); // dispid 213, slot 149
    [PreserveSig] int get_RedirectClipboard(out short pRetVal); // dispid 213, slot 150
    [PreserveSig] int put_AudioRedirectionMode(uint arg0); // dispid 215, slot 151
    [PreserveSig] int get_AudioRedirectionMode(out uint pRetVal); // dispid 215, slot 152
    [PreserveSig] int put_ConnectionBarShowPinButton(short arg0); // dispid 216, slot 153
    [PreserveSig] int get_ConnectionBarShowPinButton(out short pRetVal); // dispid 216, slot 154
    [PreserveSig] int put_PublicMode(short arg0); // dispid 217, slot 155
    [PreserveSig] int get_PublicMode(out short pRetVal); // dispid 217, slot 156
    [PreserveSig] int put_RedirectDevices(short arg0); // dispid 218, slot 157
    [PreserveSig] int get_RedirectDevices(out short pRetVal); // dispid 218, slot 158
    [PreserveSig] int put_RedirectPOSDevices(short arg0); // dispid 219, slot 159
    [PreserveSig] int get_RedirectPOSDevices(out short pRetVal); // dispid 219, slot 160
    [PreserveSig] int put_BitmapVirtualCache32BppSize(int arg0); // dispid 220, slot 161
    [PreserveSig] int get_BitmapVirtualCache32BppSize(out int pRetVal); // dispid 220, slot 162
    [PreserveSig] int put_RelativeMouseMode(short arg0); // dispid 221, slot 163
    [PreserveSig] int get_RelativeMouseMode(out short pRetVal); // dispid 221, slot 164
    [PreserveSig] int get_AuthenticationServiceClass([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 222, slot 165
    [PreserveSig] int put_AuthenticationServiceClass([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 222, slot 166
    [PreserveSig] int get_PCB([MarshalAs(UnmanagedType.BStr)] out string pRetVal); // dispid 223, slot 167
    [PreserveSig] int put_PCB([MarshalAs(UnmanagedType.BStr)] string arg0); // dispid 223, slot 168
    [PreserveSig] int put_HotKeyFocusReleaseLeft(int arg0); // dispid 224, slot 169
    [PreserveSig] int get_HotKeyFocusReleaseLeft(out int pRetVal); // dispid 224, slot 170
    [PreserveSig] int put_HotKeyFocusReleaseRight(int arg0); // dispid 225, slot 171
    [PreserveSig] int get_HotKeyFocusReleaseRight(out int pRetVal); // dispid 225, slot 172
    [PreserveSig] int put_EnableCredSspSupport(short arg0); // dispid 17, slot 173
    [PreserveSig] int get_EnableCredSspSupport(out short pRetVal); // dispid 17, slot 174
    [PreserveSig] int get_AuthenticationType(out uint pRetVal); // dispid 226, slot 175
    [PreserveSig] int put_ConnectToAdministerServer(short arg0); // dispid 227, slot 176
    [PreserveSig] int get_ConnectToAdministerServer(out short pRetVal); // dispid 227, slot 177
    [PreserveSig] int put_AudioCaptureRedirectionMode(short arg0); // dispid 228, slot 178
    [PreserveSig] int get_AudioCaptureRedirectionMode(out short pRetVal); // dispid 228, slot 179
    [PreserveSig] int put_VideoPlaybackMode(uint arg0); // dispid 229, slot 180
    [PreserveSig] int get_VideoPlaybackMode(out uint pRetVal); // dispid 229, slot 181
    [PreserveSig] int put_EnableSuperPan(short arg0); // dispid 230, slot 182
    [PreserveSig] int get_EnableSuperPan(out short pRetVal); // dispid 230, slot 183
    [PreserveSig] int put_SuperPanAccelerationFactor(uint arg0); // dispid 231, slot 184
    [PreserveSig] int get_SuperPanAccelerationFactor(out uint pRetVal); // dispid 231, slot 185
    [PreserveSig] int put_NegotiateSecurityLayer(short arg0); // dispid 232, slot 186
    [PreserveSig] int get_NegotiateSecurityLayer(out short pRetVal); // dispid 232, slot 187
    [PreserveSig] int put_AudioQualityMode(uint arg0); // dispid 233, slot 188
    [PreserveSig] int get_AudioQualityMode(out uint pRetVal); // dispid 233, slot 189
    [PreserveSig] int put_RedirectDirectX(short arg0); // dispid 234, slot 190
    [PreserveSig] int get_RedirectDirectX(out short pRetVal); // dispid 234, slot 191
    [PreserveSig] int put_NetworkConnectionType(uint arg0); // dispid 235, slot 192
    [PreserveSig] int get_NetworkConnectionType(out uint pRetVal); // dispid 235, slot 193
    [PreserveSig] int put_BandwidthDetection(short arg0); // dispid 236, slot 194
    [PreserveSig] int get_BandwidthDetection(out short pRetVal); // dispid 236, slot 195
    [PreserveSig] int put_ClientProtocolSpec(int /* ClientSpec */ arg0); // dispid 237, slot 196
    [PreserveSig] int get_ClientProtocolSpec(out int /* ClientSpec */ pRetVal); // dispid 237, slot 197
}

