// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RemoteFlow.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Folders",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    ParentId = table.Column<string>(type: "TEXT", maxLength: 36, nullable: true),
                    Path = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: false, collation: "NOCASE"),
                    Depth = table.Column<int>(type: "INTEGER", nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false),
                    IsExpanded = table.Column<bool>(type: "INTEGER", nullable: false),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    CreatedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    ModifiedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Folders", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Folders_Folders_ParentId",
                        column: x => x.ParentId,
                        principalTable: "Folders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "HostKeys",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    Host = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false, collation: "NOCASE"),
                    Port = table.Column<int>(type: "INTEGER", nullable: false),
                    KeyAlgorithm = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    PublicKeyBase64 = table.Column<string>(type: "TEXT", maxLength: 16384, nullable: false),
                    Sha256Fingerprint = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    TrustState = table.Column<int>(type: "INTEGER", nullable: false),
                    Source = table.Column<int>(type: "INTEGER", nullable: false),
                    Comment = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    FirstSeenUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    LastSeenUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HostKeys", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Settings",
                columns: table => new
                {
                    Key = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    Value = table.Column<string>(type: "TEXT", nullable: false),
                    ModifiedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Settings", x => x.Key);
                });

            migrationBuilder.CreateTable(
                name: "Tags",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false, collation: "NOCASE"),
                    ColorHex = table.Column<string>(type: "TEXT", maxLength: 7, nullable: true),
                    CreatedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tags", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Connections",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false, collation: "NOCASE"),
                    Host = table.Column<string>(type: "TEXT", maxLength: 255, nullable: false, collation: "NOCASE"),
                    Port = table.Column<int>(type: "INTEGER", nullable: false),
                    Protocol = table.Column<int>(type: "INTEGER", nullable: false),
                    Username = table.Column<string>(type: "TEXT", maxLength: 255, nullable: true),
                    AuthMethod = table.Column<int>(type: "INTEGER", nullable: false),
                    Notes = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    FolderId = table.Column<string>(type: "TEXT", maxLength: 36, nullable: true),
                    IsFavorite = table.Column<bool>(type: "INTEGER", nullable: false),
                    Environment = table.Column<int>(type: "INTEGER", nullable: false),
                    ColorOverrideHex = table.Column<string>(type: "TEXT", maxLength: 7, nullable: true),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    CreatedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    ModifiedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    Credential_Kind = table.Column<int>(type: "INTEGER", nullable: false),
                    Credential_StoreKey = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    Credential_StoreProvider = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    Credential_UpdatedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: true),
                    Ssh_KeepAliveSeconds = table.Column<int>(type: "INTEGER", nullable: true),
                    Ssh_TerminalType = table.Column<string>(type: "TEXT", maxLength: 100, nullable: false),
                    Ssh_PrivateKeyPath = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: true),
                    Ssh_InitialCommand = table.Column<string>(type: "TEXT", maxLength: 4000, nullable: true),
                    Ssh_StartupDirectory = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: true),
                    Ssh_HostKeyPolicy = table.Column<int>(type: "INTEGER", nullable: false),
                    Ssh_RequestPty = table.Column<bool>(type: "INTEGER", nullable: false),
                    Sftp_RemoteRootPath = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: true),
                    Sftp_LocalDownloadPath = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: true),
                    Sftp_PreserveTimestamps = table.Column<bool>(type: "INTEGER", nullable: false),
                    Sftp_ShowHiddenFiles = table.Column<bool>(type: "INTEGER", nullable: false),
                    Rdp_Domain = table.Column<string>(type: "TEXT", maxLength: 255, nullable: true),
                    Rdp_FullScreen = table.Column<bool>(type: "INTEGER", nullable: false),
                    Rdp_Width = table.Column<int>(type: "INTEGER", nullable: true),
                    Rdp_Height = table.Column<int>(type: "INTEGER", nullable: true),
                    Rdp_Multimon = table.Column<bool>(type: "INTEGER", nullable: false),
                    Rdp_RedirectClipboard = table.Column<bool>(type: "INTEGER", nullable: false),
                    Rdp_RedirectDrives = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Connections", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Connections_Folders_FolderId",
                        column: x => x.FolderId,
                        principalTable: "Folders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "ConnectionTags",
                columns: table => new
                {
                    ConnectionId = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    TagId = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConnectionTags", x => new { x.ConnectionId, x.TagId });
                    table.ForeignKey(
                        name: "FK_ConnectionTags_Connections_ConnectionId",
                        column: x => x.ConnectionId,
                        principalTable: "Connections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ConnectionTags_Tags_TagId",
                        column: x => x.TagId,
                        principalTable: "Tags",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "RecentConnections",
                columns: table => new
                {
                    ConnectionId = table.Column<string>(type: "TEXT", maxLength: 36, nullable: false),
                    LastOpenedUtc = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    OpenCount = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RecentConnections", x => x.ConnectionId);
                    table.ForeignKey(
                        name: "FK_RecentConnections_Connections_ConnectionId",
                        column: x => x.ConnectionId,
                        principalTable: "Connections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Connections_FolderId",
                table: "Connections",
                column: "FolderId");

            migrationBuilder.CreateIndex(
                name: "IX_Connections_Host",
                table: "Connections",
                column: "Host");

            migrationBuilder.CreateIndex(
                name: "IX_Connections_IsFavorite",
                table: "Connections",
                column: "IsFavorite",
                filter: "\"IsFavorite\" = 1");

            migrationBuilder.CreateIndex(
                name: "IX_Connections_Name",
                table: "Connections",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_Connections_Protocol",
                table: "Connections",
                column: "Protocol");

            migrationBuilder.CreateIndex(
                name: "IX_ConnectionTags_TagId_ConnectionId",
                table: "ConnectionTags",
                columns: new[] { "TagId", "ConnectionId" });

            migrationBuilder.CreateIndex(
                name: "IX_Folders_ParentId",
                table: "Folders",
                column: "ParentId");

            migrationBuilder.CreateIndex(
                name: "IX_Folders_Path",
                table: "Folders",
                column: "Path",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_HostKeys_Host_Port",
                table: "HostKeys",
                columns: new[] { "Host", "Port" });

            migrationBuilder.CreateIndex(
                name: "IX_HostKeys_Host_Port_KeyAlgorithm",
                table: "HostKeys",
                columns: new[] { "Host", "Port", "KeyAlgorithm" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_RecentConnections_LastOpenedUtc",
                table: "RecentConnections",
                column: "LastOpenedUtc",
                descending: new bool[0]);

            migrationBuilder.CreateIndex(
                name: "IX_Tags_Name",
                table: "Tags",
                column: "Name",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ConnectionTags");

            migrationBuilder.DropTable(
                name: "HostKeys");

            migrationBuilder.DropTable(
                name: "RecentConnections");

            migrationBuilder.DropTable(
                name: "Settings");

            migrationBuilder.DropTable(
                name: "Tags");

            migrationBuilder.DropTable(
                name: "Connections");

            migrationBuilder.DropTable(
                name: "Folders");
        }
    }
}
