// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteFlow.Persistence;

#nullable disable

namespace RemoteFlow.Persistence.Migrations
{
    [DbContext(typeof(RemoteFlowDbContext))]
    [Migration("20260807155313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorOverrideHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("Host");

                    b.HasIndex("IsFavorite")
                        .HasFilter("\"IsFavorite\" = 1");

                    b.HasIndex("Name");

                    b.HasIndex("Protocol");

                    b.ToTable("Connections", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.ConnectionTag", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId", "TagId");

                    b.HasIndex("TagId", "ConnectionId");

                    b.ToTable("ConnectionTags", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Folder", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.HostKey", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKeyBase64")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Fingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port");

                    b.HasIndex("Host", "Port", "KeyAlgorithm")
                        .IsUnique();

                    b.ToTable("HostKeys", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.RecentConnection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectionId");

                    b.HasIndex("LastOpenedUtc")
                        .IsDescending();

                    b.ToTable("RecentConnections", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Connection", b =>
                {
                    b.HasOne("RemoteFlow.Domain.Entities.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("RemoteFlow.Domain.ValueObjects.CredentialRef", "Credential", b1 =>
                        {
                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Kind")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Credential_Kind");

                            b1.Property<string>("StoreKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Credential_StoreKey");

                            b1.Property<string>("StoreProvider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Credential_StoreProvider");

                            b1.Property<DateTimeOffset?>("UpdatedUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("Credential_UpdatedUtc");

                            b1.HasKey("ConnectionId");

                            b1.ToTable("Connections");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");
                        });

                    b.OwnsOne("RemoteFlow.Domain.ValueObjects.RdpOptions", "Rdp", b1 =>
                        {
                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Domain")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Rdp_Domain");

                            b1.Property<bool>("FullScreen")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_FullScreen");

                            b1.Property<int?>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_Height");

                            b1.Property<bool>("Multimon")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_Multimon");

                            b1.Property<bool>("RedirectClipboard")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_RedirectClipboard");

                            b1.Property<bool>("RedirectDrives")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_RedirectDrives");

                            b1.Property<int?>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Rdp_Width");

                            b1.HasKey("ConnectionId");

                            b1.ToTable("Connections");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");
                        });

                    b.OwnsOne("RemoteFlow.Domain.ValueObjects.SftpOptions", "Sftp", b1 =>
                        {
                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LocalDownloadPath")
                                .HasMaxLength(4096)
                                .HasColumnType("TEXT")
                                .HasColumnName("Sftp_LocalDownloadPath");

                            b1.Property<bool>("PreserveTimestamps")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Sftp_PreserveTimestamps");

                            b1.Property<string>("RemoteRootPath")
                                .HasMaxLength(4096)
                                .HasColumnType("TEXT")
                                .HasColumnName("Sftp_RemoteRootPath");

                            b1.Property<bool>("ShowHiddenFiles")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Sftp_ShowHiddenFiles");

                            b1.HasKey("ConnectionId");

                            b1.ToTable("Connections");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");
                        });

                    b.OwnsOne("RemoteFlow.Domain.ValueObjects.SshOptions", "Ssh", b1 =>
                        {
                            b1.Property<string>("ConnectionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("HostKeyPolicy")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ssh_HostKeyPolicy");

                            b1.Property<string>("InitialCommand")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ssh_InitialCommand");

                            b1.Property<int?>("KeepAliveSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ssh_KeepAliveSeconds");

                            b1.Property<string>("PrivateKeyPath")
                                .HasMaxLength(4096)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ssh_PrivateKeyPath");

                            b1.Property<bool>("RequestPty")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Ssh_RequestPty");

                            b1.Property<string>("StartupDirectory")
                                .HasMaxLength(4096)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ssh_StartupDirectory");

                            b1.Property<string>("TerminalType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ssh_TerminalType");

                            b1.HasKey("ConnectionId");

                            b1.ToTable("Connections");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");
                        });

                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("Rdp")
                        .IsRequired();

                    b.Navigation("Sftp")
                        .IsRequired();

                    b.Navigation("Ssh")
                        .IsRequired();
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.ConnectionTag", b =>
                {
                    b.HasOne("RemoteFlow.Domain.Entities.Connection", null)
                        .WithMany("Tags")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteFlow.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Folder", b =>
                {
                    b.HasOne("RemoteFlow.Domain.Entities.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.RecentConnection", b =>
                {
                    b.HasOne("RemoteFlow.Domain.Entities.Connection", null)
                        .WithOne()
                        .HasForeignKey("RemoteFlow.Domain.Entities.RecentConnection", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RemoteFlow.Domain.Entities.Connection", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
