// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RemoteFlow.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddObjectStorageOptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Storage_Container",
                table: "Connections",
                type: "TEXT",
                maxLength: 63,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Storage_LocalDownloadPath",
                table: "Connections",
                type: "TEXT",
                maxLength: 4096,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Storage_Region",
                table: "Connections",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Storage_RootPrefix",
                table: "Connections",
                type: "TEXT",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Storage_ServiceUrl",
                table: "Connections",
                type: "TEXT",
                maxLength: 2048,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "Storage_UsePathStyleAddressing",
                table: "Connections",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Storage_Container",
                table: "Connections");

            migrationBuilder.DropColumn(
                name: "Storage_LocalDownloadPath",
                table: "Connections");

            migrationBuilder.DropColumn(
                name: "Storage_Region",
                table: "Connections");

            migrationBuilder.DropColumn(
                name: "Storage_RootPrefix",
                table: "Connections");

            migrationBuilder.DropColumn(
                name: "Storage_ServiceUrl",
                table: "Connections");

            migrationBuilder.DropColumn(
                name: "Storage_UsePathStyleAddressing",
                table: "Connections");
        }
    }
}
