<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/RemoteFlow.Application/RemoteFlow.Application.csproj" />
    <ProjectReference Include="../../src/RemoteFlow.Domain/RemoteFlow.Domain.csproj" />
    <ProjectReference Include="../../src/RemoteFlow.Persistence/RemoteFlow.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>
</Project>
