<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RemoteFlow.Application/RemoteFlow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="SvcSystems.UI.Terminal" />
    <PackageReference Include="XTerm.NET" />
  </ItemGroup>
</Project>
