<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NoWarn>$(NoWarn);CA1001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Porta.Pty" />
    <PackageReference Include="SvcSystems.UI.Terminal" />
  </ItemGroup>
</Project>
